# Получить все фильмы:
GET /films HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json
###

# Получить определенный фильм:
GET /films/62af63e1dd748f35bcf66943 HTTP/1.1
Host: localhost:5000
Content-Type: application/json
###

# Получить промо-фильм:
GET /promo HTTP/1.1
Host: localhost:5000
Content-Type: application/json
###

# Получить похожие фильмы:
GET /films/62af63e1dd748f35bcf66943/similar HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json
###

# Получить фильмы определенного жанра:
GET /films/genre/drama?limit=5 HTTP/1.1
Host: localhost:5000
Content-Type: application/json
###

# Создать новый фильм:
POST /films HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json

{
  "title": "В бой идут одни «старики»",
  "description": "Эта эскадрилья стала «поющей» - так капитан Титаренко подбирал себе новичков",
  "publicationDate": "2021-12-12T21:55:28.147Z",
  "genre": "drama",
  "released": "1973",
  "rating": 8,
  "previewVideoLink": "previewVideoLink",
  "videoLink": "videoLink",
  "starring": [
    "Леонид Быков",
    "Сергей Подгорный",
    "Сергей Иванов",
    "Алексей Смирнов"
  ],
  "director": "Николай Злочевский",
  "runtime": 87,
  "posterImage": "posterImage",
  "backgroundImage": "backgroundImage",
  "backgroundColor": "backgroundColor"
}
###

# Редактировать фильм:
PATCH  /films/62af63e1dd748f35bcf6696e HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json

{
  "title": "Зеленая Миля",
  "genre": "drama",
  "released": "1973",
  "rating": 9,
  "starring":["Тим Роббинс","Морган Фриман","Боб Гантон"]
}
###

# Заменить фильм:
PUT  /films/62af63e1dd748f35bcf6696e HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json

{
  "title": "В бой идут...",
  "description": "Эта эскадрилья стала «поющей» - так капитан Титаренко подбирал себе новичков",
  "publicationDate": "2021-12-12T21:55:28.147Z",
  "genre": "drama",
  "released": "1973",
  "rating": 8,
  "previewVideoLink": "previewVideoLink",
  "videoLink": "videoLink",
  "starring": [
    "Леонид Быков",
    "Сергей Подгорный",
    "Сергей Иванов",
    "Алексей Смирнов"
  ],
  "director": "Николай Злочевский",
  "runtime": 87,
  "posterImage": "posterImage",
  "backgroundImage": "backgroundImage",
  "backgroundColor": "backgroundColor"
}
###

# Удалить фильм:
DELETE  /films/62b35624acd1ac3b68aae8bf HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
###

# Создать (зарегистрировать) пользователя
POST /register HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
  "name": "Vanya Russian",
  "email": "vanya@russian.ru",
  "avatar": "avatar.png",
  "password": "torrent"
}
###

# Авторизоваться (получить токен)
POST /login HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
  "email": "vanya5@russian.ru",
  "password": "torrent"
}
###

# Завершить сеанс
DELETE /logout HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA

###

# Проверить авторизацию
GET /login HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA

###

#  Отправка аватарки пользователю
POST /6281421bab1588f282087ef1/avatar HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="04.jpg"
Content-Type: image/jpeg

< D:/загрузки/04.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# Создать комментарий
POST /comments/62af63e1dd748f35bcf669bb HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
Content-Type: application/json

{
  "comment": "Это короткий комментарий",
  "rating": 9
}

###

# Получить список комментариев к фильму
GET /comments/62af63e1dd748f35bcf669bb?limit=20 HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA

###

# Получить список "К просмотру"
GET /favorite HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
###

# Добавить фильм в список "К просмотру"
POST  /favorite/62af63e1dd748f35bcf669bb/1 HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
###

# Удалить фильм из списка "К просмотру"
POST /favorite/62af63e1dd748f35bcf66908/0 HTTP/1.1
Host: localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZhbnlhNUBydXNzaWFuLnJ1IiwidXNlcklkIjoiNjJiMDMxOGU5ZmIwYmFjN2QxMGRkOGVjIiwibmFtZSI6IiBSdXNzaWFuIiwiYXZhdGFyIjoiYXZhdGFyLnBuZyIsImlhdCI6MTY1NTk5NzA1OCwiZXhwIjoxNjU2MDQwMjU4fQ.zfz0RHYQwm7rIjltPgwT2zg0ShTmcyXbFkFQKXepWfA
###
