const DEFAULT_FILM_COUNT = 60;
const SIMILAR_FILM_COUNT = 4;
const DEFAULT_FILM_SKIP_COUNT = 0;
const SIMILAR_FILM_SKIP_COUNT = 1;

export {
  DEFAULT_FILM_COUNT,
  SIMILAR_FILM_COUNT,
  DEFAULT_FILM_SKIP_COUNT,
  SIMILAR_FILM_SKIP_COUNT
};
